[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports_ignore = ["test", "script"]
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@solbase/=lib/solbase/src/",
    "murky/=lib/murky/",
]

solc = "0.8.25"
optimizer = true
optimizer_runs = 10000

[fmt]
tab_width = 4
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
